### ISSUE TITLE
pub get upgrade dependencies not working 

### ISSUE THREAD

**Issue by zakblacki** [martin-braun/google_maps_place_picker_mb#19]
This  has ben going for awhile every new version pub get google_maps_place_picker_mb: ^2.0.0-mb.17 will not work kindly fix these versioning issues 

![image](https://user-images.githubusercontent.com/29728429/166643106-6a823a5f-8947-4fc1-8ba0-4e9538eb0d56.png)

**Comment by martin-braun** [comment]
@zakblacki Unfortunately, I don't think this has anything to do with this package, I'm not responsible for connectivity issues between you and the pub.dev servers and the servers don't belong to me. 

If you visit https://pub.dev/packages/google_maps_place_picker_mb/versions, you should be able to verify that versions are properly uploaded. If you have issues in generell, you could bypass this issue with a VPN. At the end, I publish my package like everybody else, so it shall be just coincidences that it happens when a new version of my package is released. You should have such issues for any new packages, since the servers are the same. 

I ask you kindly to open an issue over at https://github.com/flutter/flutter or https://github.com/dart-lang/pub-dev/issues

Thank you.
