### ISSUE TITLE
Flutter 3.0.0 Migration

### ISSUE THREAD

**Issue by holy-dev** [martin-braun/google_maps_place_picker_mb#21]
**Describe the bug**
Not working with Flutter 3.0.0

**To Reproduce**
1. Build

**Comment by brianmutiso** [comment]
Because google_maps_place_picker_mb >=2.0.0-mb.2 depends on location from hosted and kizusi depends on location from git, google_maps_place_picker_mb >=2.0.0-mb.2 is forbidden.
So, because kizusi depends on google_maps_place_picker_mb ^2.0.0-mb.16, version solving failed.
pub get failed (1; So, because kizusi depends on google_maps_place_picker_mb ^2.0.0-mb.16, version solving failed.)

**Comment by brianmutiso** [comment]
Because google_maps_place_picker_mb >=2.0.0-mb.2 depends on location from hosted and project depends on location from git, google_maps_place_picker_mb >=2.0.0-mb.2 is forbidden.
So, because project depends on google_maps_place_picker_mb ^2.0.0-mb.16, version solving failed.
pub get failed (1; So, because project depends on google_maps_place_picker_mb ^2.0.0-mb.16, version solving failed.)

**Comment by martin-braun** [comment]
Google released 3.0.0 without releasing it on the beta channel first, so I had no chance to test it other than using their master branch, which is really painful to deal with. I will look into this, soon.

If you need to compile, please consider to look into [fvm](fvm.app) to get your app running and working in the meantime.
