### ISSUE TITLE
Geolocator dependency bump to 9.0.0

### ISSUE THREAD

**Issue by Wian-TMC** [martin-braun/google_maps_place_picker_mb#33]
Just a heads up to update dependency for geolocator to 9.0.0

**Comment by martin-braun** [comment]
@Wian-TMC I'm aware of this and we have to do it sooner or later to support `compileSdkVersion 33` and up, but I cannot upgrade the package unless I drop support for Flutter 2, which I try to avoid as long as possible. Please check [this issue](https://github.com/Baseflow/flutter-geolocator/issues/1084) to get more details.

**Comment by Wian-TMC** [comment]
Cool! Let's wait and see

**Comment by dpedrinha** [comment]
I'm having trouble continuing my project because of this.
One of my plugins require android compile sdk 33 and now these two plugins are conflicting.
To make things worse, I updated everything in an attempt to solve the problem (dart, flutter, android studio, plugins and etc). 
Am I screwed?
I'm very bad at this kind of framework problems. Have no idea what to do. I'm stuck and it seems this plugin won't update anytime soon due to the reasons mentioned above.
:.(

**Comment by martin-braun** [comment]
@dpedrinha I sorry for your inconvenience. I fixed this issue, but felt confident that we might get #24 pushed through. Unfortunately, we have to wait for Google. I pushed a new version `mb.21` which will use the Geolocator `9.0.1`. `9.0.0` is not supported for this package. 

Good luck.

**Comment by dpedrinha** [comment]
> @dpedrinha I'm sorry for your inconvenience. This issue was already fixed, but I felt confident that we might get #24 pushed through. Unfortunately, we have to wait for Google. I pushed a new version `mb.21` which will use the geolocator `9.0.1`, I hope this will work out for you. `9.0.0` is not supported for this package.
> 
> Good luck.

I'm able to compile now. Thank you very much.
