### ISSUE TITLE
Replace Google Maps with flutter_map?

### ISSUE THREAD

**Issue by giorgio79** [martin-braun/google_maps_place_picker_mb#42]
given the high crash rate of Google Maps https://github.com/flutter/flutter/issues/105965

any plans to switch to https://pub.dev/packages/flutter_map ? :) We could decouple this fantastic packge from Google MAps

**Comment by martin-braun** [comment]
Hi @giorgio79. In a generell, I like your idea. I'm very disappointed in Google and how they handled the situation. Fortunately, I'm not affected by the crashes, because my app is still driven on Flutter 2. 

If I had more time, I would probably make a fork and implement `flutter_map` myself as the name of this plugin implies that it's for Google Maps. In the long run, I want to free my creations from big tech dependencies, the privacy of my users is reason enough to do so. As of now, my customer wants to use Google Maps and since there are no crashes on Flutter 2 I would have to work on this in my free time, which is unlikely to happen in the near future, since I'm very busy on commercial projects at the moment.

**Comment by giorgio79** [comment]
Thx Martin! Looks like the bug is fixed with Google Maps, and after some study it looks like flutter_map does not support Google Maps which would make it difficult to switch back... closing this request for now
